In [43]:
#########################    EXP1      #####################
'''Implement Recursive Depth First Search Algorithm. Read the undirected
unweighted graph from a .csv file. '''
import pandas as pd

# Function to read the graph from a CSV file
def read_graph_from_csv(file_path):
    df = pd.read_csv(file_path)
    graph = {}
    for i in range(len(df)):
        node1 = df.iloc[i, 0]
        node2 = df.iloc[i, 1]
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append(node2)
        graph[node2].append(node1)  # Because the graph is undirected
    return graph

# Recursive DFS function
def dfs_recursive(graph, node, visited):
    if node not in visited:
        print(node, end=" ")
        visited.add(node)
        for neighbor in graph[node]:
            dfs_recursive(graph, neighbor, visited)

# Main Execution
if __name__ == "__main__":
    # Specify file name manually
    file_name = "C:\\Users\\shank\\Downloads\\csvforExp1.csv"  # <-- Put your actual file name here
    
    # Read the graph from the uploaded CSV file
    graph = read_graph_from_csv(file_name)
    
    print("Graph Representation:", graph)
    
    # Ask for the starting node from the user
    start_node = input("Enter the starting node for DFS: ")
    
    # Perform DFS traversal
    print("DFS Traversal:")
    dfs_recursive(graph, start_node, set())

Graph Representation: {'A': ['C'], 'C': ['A', 'E'], 'B': ['D'], 'D': ['B', 'E'], 'E': ['C', 'D']}


Enter the starting node for DFS:  A


DFS Traversal:
A C E D B 

In [4]:
#########################    EXP2      #####################
'''Implement Non-Recursive Depth First Search Algorithm. Read the
undirected unweighted graph from user. 
'''
# Function to read the graph from user input
def read_graph_from_user():
    graph = {}
    print("Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.")
    while True:
        edge = input("Enter an edge (node1 node2): ")
        if edge.lower() == 'done':
            break
        node1, node2 = edge.split()

        # Add nodes to the graph
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []

        graph[node1].append(node2)
        graph[node2].append(node1)  # Undirected graph: add both directions

    return graph

# Non-recursive DFS function using stack
def dfs_non_recursive(graph, start_node):
    visited = set()  # To track visited nodes
    stack = [start_node]  # Initialize stack with the start node

    while stack:
        node = stack.pop()  # Pop the last node from the stack

        if node not in visited:
            print(node, end=" ")  # Print the node as we visit it
            visited.add(node)  # Mark the node as visited

            # Add all unvisited neighbors to the stack
            for neighbor in graph[node]:
                if neighbor not in visited:
                    stack.append(neighbor)

# Main Execution
if __name__ == "__main__":
    # Read the graph from the user
    graph = read_graph_from_user()

    print("Graph Representation:", graph)

    # Ask for the starting node from the user
    start_node = input("Enter the starting node for DFS: ")

    # Perform DFS traversal
    print("DFS Traversal (Non-Recursive):")
    dfs_non_recursive(graph, start_node)


Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.


Enter an edge (node1 node2):  a b
Enter an edge (node1 node2):  a c
Enter an edge (node1 node2):  b d
Enter an edge (node1 node2):  b e
Enter an edge (node1 node2):  c f
Enter an edge (node1 node2):  done


Graph Representation: {'a': ['b', 'c'], 'b': ['a', 'd', 'e'], 'c': ['a', 'f'], 'd': ['b'], 'e': ['b'], 'f': ['c']}


Enter the starting node for DFS:  a


DFS Traversal (Non-Recursive):
a c f b e d 

In [5]:
#########################    EXP3      #####################
''' Implement Breadth First Search Algorithm. Read the undirected
unweighted graph from user. 
'''

# Function to read the graph from user input
def read_graph_from_user():
    graph = {}
    print("Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.")
    while True:
        edge = input("Enter an edge (node1 node2): ")
        if edge.lower() == 'done':
            break
        node1, node2 = edge.split()

        # Add nodes to the graph
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []

        graph[node1].append(node2)
        graph[node2].append(node1)  # Undirected graph: add both directions

    return graph

# Breadth First Search function using queue
def bfs(graph, start_node):
    visited = set()  # To track visited nodes
    queue = [start_node]  # Initialize queue with the start node

    while queue:
        node = queue.pop(0)  # Dequeue the front node from the queue

        if node not in visited:
            print(node, end=" ")  # Print the node as we visit it
            visited.add(node)  # Mark the node as visited

            # Add all unvisited neighbors to the queue
            for neighbor in graph[node]:
                if neighbor not in visited:
                    queue.append(neighbor)

# Main Execution
if __name__ == "__main__":
    # Read the graph from the user
    graph = read_graph_from_user()

    print("Graph Representation:", graph)

    # Ask for the starting node from the user
    start_node = input("Enter the starting node for BFS: ")

    # Perform BFS traversal
    print("BFS Traversal:")
    bfs(graph, start_node)


Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.


Enter an edge (node1 node2):  a b
Enter an edge (node1 node2):  a c
Enter an edge (node1 node2):  b d
Enter an edge (node1 node2):  b e
Enter an edge (node1 node2):  c f
Enter an edge (node1 node2):  done


Graph Representation: {'a': ['b', 'c'], 'b': ['a', 'd', 'e'], 'c': ['a', 'f'], 'd': ['b'], 'e': ['b'], 'f': ['c']}


Enter the starting node for BFS:  a


BFS Traversal:
a b c d e f 

In [6]:
#########################    EXP4      #####################
''' Implement Best First Search Algorithm. Read the directed unweighted
graph and the heuristic values from user.'''

import heapq  # For the priority queue (min-heap)

# Function to read the graph and heuristic values from user input
def read_graph_and_heuristics():
    graph = {}
    heuristics = {}

    print("Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.")
    while True:
        edge = input("Enter an edge (node1 node2): ")
        if edge.lower() == 'done':
            break
        node1, node2 = edge.split()

        if node1 not in graph:
            graph[node1] = []
        graph[node1].append(node2)  # Directed edge from node1 to node2

        if node2 not in graph:
            graph[node2] = []  # Make sure to add node2 as well in case it's not there

    print("Enter heuristic values for each node.")
    # Automatically ask for heuristic values for all nodes present in the graph
    all_nodes = set(graph.keys())
    for node in all_nodes:
        if node not in heuristics:
            heuristic = float(input(f"Enter heuristic value for {node}: "))
            heuristics[node] = heuristic

    return graph, heuristics

# Best First Search algorithm using a priority queue (min-heap)
def best_first_search(graph, heuristics, start_node):
    visited = set()  # To track visited nodes
    priority_queue = []  # Priority queue to explore nodes based on heuristic

    # Push the start node with its heuristic value to the queue
    heapq.heappush(priority_queue, (heuristics[start_node], start_node))

    while priority_queue:
        _, current_node = heapq.heappop(priority_queue)  # Get the node with the lowest heuristic value

        if current_node not in visited:
            print(current_node, end=" ")  # Print the node as we visit it
            visited.add(current_node)  # Mark it as visited

            # Add unvisited neighbors to the priority queue
            for neighbor in graph.get(current_node, []):
                if neighbor not in visited:
                    heapq.heappush(priority_queue, (heuristics[neighbor], neighbor))

# Main Execution
if __name__ == "__main__":
    # Read the graph and heuristics from the user
    graph, heuristics = read_graph_and_heuristics()

    print("Graph Representation:", graph)
    print("Heuristic Values:", heuristics)

    # Ask for the starting node from the user
    start_node = input("Enter the starting node for Best First Search: ")

    # Perform Best First Search traversal
    print("Best First Search Traversal:")
    best_first_search(graph, heuristics, start_node)


Enter edges of the graph in the format 'node1 node2'. Type 'done' when finished.


Enter an edge (node1 node2):  a b
Enter an edge (node1 node2):  a c
Enter an edge (node1 node2):  b d
Enter an edge (node1 node2):  c d
Enter an edge (node1 node2):  done


Enter heuristic values for each node.


Enter heuristic value for d:  3
Enter heuristic value for a:  2
Enter heuristic value for b:  1
Enter heuristic value for c:  0


Graph Representation: {'a': ['b', 'c'], 'b': ['d'], 'c': ['d'], 'd': []}
Heuristic Values: {'d': 3.0, 'a': 2.0, 'b': 1.0, 'c': 0.0}


Enter the starting node for Best First Search:  a


Best First Search Traversal:
a c b d 

In [7]:
#########################    EXP5      #####################
''' Implement Best First Search Algorithm. Read the undirected weighted
graph and the heuristic values from user. 
'''

import heapq  # For the priority queue (min-heap)

# Function to read the graph and heuristic values from user input
def read_graph_and_heuristics():
    graph = {}
    heuristics = {}

    print("Enter edges of the graph in the format 'node1 node2 weight'. Type 'done' when finished.")
    while True:
        edge = input("Enter an edge (node1 node2 weight): ")
        if edge.lower() == 'done':
            break
        node1, node2, weight = edge.split()
        weight = float(weight)

        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []

        # Since the graph is undirected, add both directions
        graph[node1].append((node2, weight))
        graph[node2].append((node1, weight))

    print("Enter heuristic values for each node.")
    # Automatically ask for heuristic values for all nodes present in the graph
    all_nodes = set(graph.keys())
    for node in all_nodes:
        if node not in heuristics:
            heuristic = float(input(f"Enter heuristic value for {node}: "))
            heuristics[node] = heuristic

    return graph, heuristics

# Best First Search algorithm using a priority queue (min-heap)
def best_first_search(graph, heuristics, start_node):
    visited = set()  # To track visited nodes
    priority_queue = []  # Priority queue to explore nodes based on heuristic

    # Push the start node with its heuristic value to the queue
    heapq.heappush(priority_queue, (heuristics[start_node], start_node))

    while priority_queue:
        _, current_node = heapq.heappop(priority_queue)  # Get the node with the lowest heuristic value

        if current_node not in visited:
            print(current_node, end=" ")  # Print the node as we visit it
            visited.add(current_node)  # Mark it as visited

            # Add unvisited neighbors to the priority queue based on heuristic values
            for neighbor, _ in graph.get(current_node, []):
                if neighbor not in visited:
                    heapq.heappush(priority_queue, (heuristics[neighbor], neighbor))

# Main Execution
if __name__ == "__main__":
    # Read the graph and heuristics from the user
    graph, heuristics = read_graph_and_heuristics()

    print("Graph Representation:", graph)
    print("Heuristic Values:", heuristics)

    # Ask for the starting node from the user
    start_node = input("Enter the starting node for Best First Search: ")

    # Perform Best First Search traversal
    print("Best First Search Traversal:")
    best_first_search(graph, heuristics, start_node)


Enter edges of the graph in the format 'node1 node2 weight'. Type 'done' when finished.


Enter an edge (node1 node2 weight):  a b 1
Enter an edge (node1 node2 weight):  a c 3
Enter an edge (node1 node2 weight):  b d 2
Enter an edge (node1 node2 weight):  c d 1
Enter an edge (node1 node2 weight):  done


Enter heuristic values for each node.


Enter heuristic value for d:  3
Enter heuristic value for a:  2
Enter heuristic value for b:  1
Enter heuristic value for c:  0


Graph Representation: {'a': [('b', 1.0), ('c', 3.0)], 'b': [('a', 1.0), ('d', 2.0)], 'c': [('a', 3.0), ('d', 1.0)], 'd': [('b', 2.0), ('c', 1.0)]}
Heuristic Values: {'d': 3.0, 'a': 2.0, 'b': 1.0, 'c': 0.0}


Enter the starting node for Best First Search:  a


Best First Search Traversal:
a c b d 

In [8]:
#########################    EXP6      #####################
''' Implement Best First Search Algorithm. Read the undirected unweighted
graph and the heuristic values from user. 
'''
import heapq

# Function for Best First Search traversal
def best_first_search(graph, heuristics, start_node):
    # Priority queue to store nodes with their heuristic values
    priority_queue = []

    # Add the starting node with its heuristic value to the queue
    heapq.heappush(priority_queue, (heuristics.get(start_node, float('inf')), start_node))

    visited = set()

    while priority_queue:
        # Get the node with the smallest heuristic value
        current_heuristic, current_node = heapq.heappop(priority_queue)

        # If the node is already visited, skip it
        if current_node in visited:
            continue

        # Visit the node
        print(current_node, end=" ")
        visited.add(current_node)

        # Add unvisited neighbors to the queue based on their heuristic values
        for neighbor in graph.get(current_node, []):
            if neighbor not in visited:
                # Use the heuristic value from the input or assign float('inf') if not present
                heapq.heappush(priority_queue, (heuristics.get(neighbor, float('inf')), neighbor))

# Read graph from user input
def read_graph():
    graph = {}
    while True:
        edge = input("Enter an edge (node1 node2) or 'done' to finish: ").strip()
        if edge.lower() == 'done':
            break
        node1, node2 = edge.split()

        # Add the edge to the graph
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append(node2)
        graph[node2].append(node1)

    return graph

# Read heuristic values from user input
def read_heuristics():
    heuristics = {}
    while True:
        node = input("Enter node for heuristic value or 'done' to finish: ").strip()
        if node.lower() == 'done':
            break
        heuristic_value = float(input(f"Enter heuristic value for {node}: ").strip())
        heuristics[node] = heuristic_value
    return heuristics

# Main function to execute the Best First Search
def main():
    print("Enter the edges of the graph:")
    graph = read_graph()

    print("Enter the heuristic values for each node:")
    heuristics = read_heuristics()

    start_node = input("Enter the starting node for Best First Search: ").strip()

    print("\nBest First Search Traversal:")
    best_first_search(graph, heuristics, start_node)

# Run the program
if __name__ == "__main__":
    main()


Enter the edges of the graph:


Enter an edge (node1 node2) or 'done' to finish:  a b
Enter an edge (node1 node2) or 'done' to finish:  a c
Enter an edge (node1 node2) or 'done' to finish:  b d
Enter an edge (node1 node2) or 'done' to finish:  done


Enter the heuristic values for each node:


Enter node for heuristic value or 'done' to finish:  a
Enter heuristic value for a:  3
Enter node for heuristic value or 'done' to finish:  b
Enter heuristic value for b:  2
Enter node for heuristic value or 'done' to finish:  c
Enter heuristic value for c:  1
Enter node for heuristic value or 'done' to finish:  done
Enter the starting node for Best First Search:  a



Best First Search Traversal:
a c b d 

In [9]:
#########################    EXP7      #####################
'''Implement Best First Search Algorithm. Read the directed weighted graph
and the heuristic values from user. '''

import heapq

# Function for Best First Search traversal on directed weighted graph
def best_first_search(graph, heuristics, start_node):
    # Priority queue to store nodes with their heuristic values
    priority_queue = []

    # Add the starting node with its heuristic value to the queue
    heapq.heappush(priority_queue, (heuristics.get(start_node, float('inf')), start_node))

    visited = set()

    while priority_queue:
        # Get the node with the smallest heuristic value
        current_heuristic, current_node = heapq.heappop(priority_queue)

        # If the node is already visited, skip it
        if current_node in visited:
            continue

        # Visit the node
        print(current_node, end=" ")
        visited.add(current_node)

        # Add unvisited neighbors to the queue based on their heuristic values
        for neighbor, _ in graph.get(current_node, []):  # Ignore the weight, only use neighbors
            if neighbor not in visited:
                # Use the heuristic value from the input or assign float('inf') if not present
                heapq.heappush(priority_queue, (heuristics.get(neighbor, float('inf')), neighbor))

# Read directed weighted graph from user input
def read_graph():
    graph = {}
    while True:
        edge = input("Enter an edge (node1 node2 weight) or 'done' to finish: ").strip()
        if edge.lower() == 'done':
            break
        node1, node2, weight = edge.split()
        weight = float(weight)

        # Add the directed edge to the graph
        if node1 not in graph:
            graph[node1] = []
        graph[node1].append((node2, weight))

    return graph

# Read heuristic values from user input
def read_heuristics():
    heuristics = {}
    while True:
        node = input("Enter node for heuristic value or 'done' to finish: ").strip()
        if node.lower() == 'done':
            break
        heuristic_value = float(input(f"Enter heuristic value for {node}: ").strip())
        heuristics[node] = heuristic_value
    return heuristics

# Main function to execute the Best First Search
def main():
    print("Enter the directed weighted edges of the graph:")
    graph = read_graph()

    print("Enter the heuristic values for each node:")
    heuristics = read_heuristics()

    start_node = input("Enter the starting node for Best First Search: ").strip()

    print("\nBest First Search Traversal:")
    best_first_search(graph, heuristics, start_node)

# Run the program
if __name__ == "__main__":
    main()


Enter the directed weighted edges of the graph:


Enter an edge (node1 node2 weight) or 'done' to finish:  a b 1
Enter an edge (node1 node2 weight) or 'done' to finish:  a c 3
Enter an edge (node1 node2 weight) or 'done' to finish:  b d 2
Enter an edge (node1 node2 weight) or 'done' to finish:  c d 1
Enter an edge (node1 node2 weight) or 'done' to finish:  done


Enter the heuristic values for each node:


Enter node for heuristic value or 'done' to finish:  a
Enter heuristic value for a:  3
Enter node for heuristic value or 'done' to finish:  b
Enter heuristic value for b:  2
Enter node for heuristic value or 'done' to finish:  c
Enter heuristic value for c:  1
Enter node for heuristic value or 'done' to finish:  d
Enter heuristic value for d:  0
Enter node for heuristic value or 'done' to finish:  done
Enter the starting node for Best First Search:  a



Best First Search Traversal:
a c d b 

In [13]:
#########################    EXP8      #####################

#A* directed weighted graph and heuristic csv

import csv
import heapq

# Function to read graph from CSV file
def read_graph_from_csv(graph_file, heuristic_file):
    graph = {}
    heuristics = {}

    # Read graph data (edges with weights)
    with open(graph_file, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            node1 = row['node1']
            node2 = row['node2']
            weight = float(row['weight'])

            if node1 not in graph:
                graph[node1] = []
            graph[node1].append((node2, weight))

    # Read heuristic values
    with open(heuristic_file, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            node = row['node']
            heuristic = float(row['heuristic_value'])
            heuristics[node] = heuristic

    return graph, heuristics

# A* Algorithm
def a_star_algorithm(graph, heuristics, start, goal):
    open_list = []  # Priority queue (min-heap)
    heapq.heappush(open_list, (heuristics[start], 0, start))  # (f(n), tiebreaker, node)

    g_costs = {start: 0}  # g(n): cost from start to current node
    came_from = {}  # To reconstruct the path

    visited = set()  # Keep track of visited nodes
    count = 0  # Tiebreaker for equal f-values

    while open_list:
        _, _, current_node = heapq.heappop(open_list)

        if current_node in visited:
            continue

        visited.add(current_node)

        if current_node == goal:
            # Reconstruct the path
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start)
            path.reverse()
            return path, g_costs[goal]  # Return path and total cost

        for neighbor, weight in graph.get(current_node, []):
            if neighbor in visited:
                continue

            tentative_g_cost = g_costs[current_node] + weight

            if neighbor not in g_costs or tentative_g_cost < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g_cost
                f_cost = tentative_g_cost + heuristics.get(neighbor, 0)
                count += 1  # Ensure unique ordering in the heap
                heapq.heappush(open_list, (f_cost, count, neighbor))
                came_from[neighbor] = current_node

    return None, float('inf')  # No path found

# Main Execution
def main():
    try:
        # Take the file paths from the user
        graph_file = input("Enter the path of the graph CSV file: ")
        heuristic_file = input("Enter the path of the heuristic CSV file: ")

        # Read graph and heuristic data from the provided files
        graph, heuristics = read_graph_from_csv(graph_file, heuristic_file)

        print("\nGraph Representation:")
        for node, neighbors in graph.items():
            print(f"  {node} -> {neighbors}")

        print("\nHeuristic Values:")
        for node, value in heuristics.items():
            print(f"  {node}: {value}")

        # Get start and goal nodes from user
        start_node = input("\nEnter the starting node for A* Search: ")
        goal_node = input("Enter the goal node for A* Search: ")

        # Validate start and goal nodes
        if start_node not in graph:
            print(f"Error: Start node '{start_node}' is not in the graph!")
            return
        if goal_node not in heuristics:
            print(f"Error: Goal node '{goal_node}' is not in the graph!")
            return

        # Perform A* Search
        path, total_cost = a_star_algorithm(graph, heuristics, start_node, goal_node)

        if path:
            print("\nA* Search Results:")
            print("Path:", " -> ".join(path))
            print("Total Cost:", total_cost)

            # Show step-by-step evaluation
            print("\nStep-by-step node evaluation:")
            current_cost = 0
            for i in range(len(path)-1):
                current = path[i]
                next_node = path[i+1]
                for neighbor, weight in graph.get(current, []):
                    if neighbor == next_node:
                        node_cost = weight
                        current_cost += node_cost
                        break

                print(f"  {current} to {next_node}: g={current_cost}, h={heuristics[next_node]}, f={current_cost + heuristics[next_node]}")
        else:
            print("\nNo path found from", start_node, "to", goal_node)

    except FileNotFoundError as e:
        print(f"Error: File not found - {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Run the program
if __name__ == "__main__":
    main()

Enter the path of the graph CSV file:  C:\Users\shank\Downloads\csvforExp8Graph.csv
Enter the path of the heuristic CSV file:  C:\Users\shank\Downloads\csvforExp8Heru.csv



Graph Representation:
  a -> [('b', 1.0), ('c', 3.0)]
  b -> [('d', 2.0)]
  c -> [('d', 1.0)]

Heuristic Values:
  a: 3.0
  b: 2.0
  c: 1.0
  d: 0.0



Enter the starting node for A* Search:  a
Enter the goal node for A* Search:  d



A* Search Results:
Path: a -> b -> d
Total Cost: 3.0

Step-by-step node evaluation:
  a to b: g=1.0, h=2.0, f=3.0
  b to d: g=3.0, h=0.0, f=3.0


In [14]:
#########################    EXP9      #####################

# A* directed weighted graph and heuristic from user

import heapq

# A* Algorithm
def a_star_algorithm(graph, heuristics, start, goal):
    open_list = []  # Priority queue (min-heap)
    heapq.heappush(open_list, (heuristics[start], start))  # (f(n), node)

    g_costs = {start: 0}  # g(n): cost from start to current node
    came_from = {}  # To reconstruct the path

    while open_list:
        _, current_node = heapq.heappop(open_list)

        if current_node == goal:
            # Reconstruct the path
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start)
            path.reverse()
            return path

        for neighbor, weight in graph.get(current_node, []):
            tentative_g_cost = g_costs[current_node] + weight

            if neighbor not in g_costs or tentative_g_cost < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g_cost
                f_cost = tentative_g_cost + heuristics.get(neighbor, 0)
                heapq.heappush(open_list, (f_cost, neighbor))
                came_from[neighbor] = current_node

    return None  # No path found

# Function to read the graph and heuristics from user input
def read_graph_and_heuristics():
    graph = {}
    heuristics = {}

    # Read the graph (directed weighted edges)
    print("Enter the directed weighted edges of the graph:")
    while True:
        edge = input("Enter an edge (node1 node2 weight) or 'done' to finish: ")
        if edge == 'done':
            break
        node1, node2, weight = edge.split()
        weight = float(weight)
        if node1 not in graph:
            graph[node1] = []
        graph[node1].append((node2, weight))

    # Read heuristic values
    print("Enter the heuristic values for each node:")
    while True:
        node = input("Enter node for heuristic value or 'done' to finish: ")
        if node == 'done':
            break
        heuristic = float(input(f"Enter heuristic value for {node}: "))
        heuristics[node] = heuristic

    return graph, heuristics

# Main Execution
def main():
    # Read the graph and heuristics from user input
    graph, heuristics = read_graph_and_heuristics()

    print("Graph Representation:", graph)
    print("Heuristic Values:", heuristics)

    # Get start and goal nodes from user
    start_node = input("Enter the starting node for A* Search: ")
    goal_node = input("Enter the goal node for A* Search: ")

    # Perform A* Search
    path = a_star_algorithm(graph, heuristics, start_node, goal_node)

    if path:
        print("A* Search Path:", " -> ".join(path))
    else:
        print("No path found!")

# Run the program
if __name__ == "__main__":
    main()


Enter the directed weighted edges of the graph:


Enter an edge (node1 node2 weight) or 'done' to finish:  a b 1
Enter an edge (node1 node2 weight) or 'done' to finish:  a c 3
Enter an edge (node1 node2 weight) or 'done' to finish:  b d 2
Enter an edge (node1 node2 weight) or 'done' to finish:  c d 1
Enter an edge (node1 node2 weight) or 'done' to finish:  done


Enter the heuristic values for each node:


Enter node for heuristic value or 'done' to finish:  a
Enter heuristic value for a:  3
Enter node for heuristic value or 'done' to finish:  b
Enter heuristic value for b:  2
Enter node for heuristic value or 'done' to finish:  c
Enter heuristic value for c:  1
Enter node for heuristic value or 'done' to finish:  d
Enter heuristic value for d:  0
Enter node for heuristic value or 'done' to finish:  done


Graph Representation: {'a': [('b', 1.0), ('c', 3.0)], 'b': [('d', 2.0)], 'c': [('d', 1.0)]}
Heuristic Values: {'a': 3.0, 'b': 2.0, 'c': 1.0, 'd': 0.0}


Enter the starting node for A* Search:  a
Enter the goal node for A* Search:  d


A* Search Path: a -> b -> d


In [15]:
#########################    EXP 10     #####################
# A* undirected weighted graph and heuristic csv

import pandas as pd
import heapq

# A* Algorithm
def a_star_algorithm(graph, heuristics, start, goal):
    open_list = []  # Priority queue (min-heap)
    heapq.heappush(open_list, (heuristics[start], start))  # (f(n), node)

    g_costs = {start: 0}  # g(n): cost from start to current node
    came_from = {}  # To reconstruct the path

    while open_list:
        _, current_node = heapq.heappop(open_list)

        if current_node == goal:
            # Reconstruct the path
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start)
            path.reverse()
            return path

        for neighbor, weight in graph.get(current_node, []):
            tentative_g_cost = g_costs[current_node] + weight

            if neighbor not in g_costs or tentative_g_cost < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g_cost
                f_cost = tentative_g_cost + heuristics.get(neighbor, 0)
                heapq.heappush(open_list, (f_cost, neighbor))
                came_from[neighbor] = current_node

    return None  # No path found

# Function to read the graph from CSV file
def read_graph_from_csv(file_path):
    df = pd.read_csv(file_path)
    graph = {}

    # Populate the graph from the edges
    for i in range(len(df)):
        node1 = df.iloc[i, 0]
        node2 = df.iloc[i, 1]
        weight = float(df.iloc[i, 2])

        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []

        # Since the graph is undirected, add both directions
        graph[node1].append((node2, weight))
        graph[node2].append((node1, weight))

    return graph

# Function to read heuristic values from CSV file
def read_heuristics_from_csv(file_path):
    df = pd.read_csv(file_path)
    heuristics = {}

    # Populate the heuristics dictionary
    for i in range(len(df)):
        node = df.iloc[i, 0]
        heuristic_value = float(df.iloc[i, 1])
        heuristics[node] = heuristic_value

    return heuristics

# Main Execution
def main():
    # Get the paths for the CSV files
    graph_file = input("Enter the file path for the graph CSV: ")
    heuristics_file = input("Enter the file path for the heuristics CSV: ")

    # Read the graph and heuristics from CSV files
    graph = read_graph_from_csv(graph_file)
    heuristics = read_heuristics_from_csv(heuristics_file)

    print("Graph Representation:", graph)
    print("Heuristic Values:", heuristics)

    # Get start and goal nodes from user
    start_node = input("Enter the starting node for A* Search: ")
    goal_node = input("Enter the goal node for A* Search: ")

    # Perform A* Search
    path = a_star_algorithm(graph, heuristics, start_node, goal_node)

    if path:
        print("A* Search Path:", " -> ".join(path))
    else:
        print("No path found!")

# Run the program
if __name__ == "__main__":
    main()



Enter the file path for the graph CSV:  C:\Users\shank\Downloads\csvforExp8Graph.csv
Enter the file path for the heuristics CSV:  C:\Users\shank\Downloads\csvforExp8Heru.csv


Graph Representation: {'a': [('b', 1.0), ('c', 3.0)], 'b': [('a', 1.0), ('d', 2.0)], 'c': [('a', 3.0), ('d', 1.0)], 'd': [('b', 2.0), ('c', 1.0)]}
Heuristic Values: {'a': 3.0, 'b': 2.0, 'c': 1.0, 'd': 0.0}


Enter the starting node for A* Search:  a
Enter the goal node for A* Search:  d


A* Search Path: a -> b -> d


In [16]:
#########################    EXP 11     #####################
# A* undirected weighted graph and heuristic from user

import heapq

# Function to perform A* algorithm
def a_star_algorithm(graph, heuristics, start, goal):
    open_list = []  # Priority queue (min-heap)
    heapq.heappush(open_list, (heuristics[start], start))  # (f(n), node)

    g_costs = {start: 0}  # g(n): cost from start to current node
    f_costs = {start: heuristics[start]}  # f(n) = g(n) + h(n)

    came_from = {}  # To reconstruct the path

    while open_list:
        _, current_node = heapq.heappop(open_list)

        if current_node == goal:
            # Reconstruct the path
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start)
            path.reverse()
            return path

        for neighbor, weight in graph.get(current_node, []):
            tentative_g_cost = g_costs[current_node] + weight

            if neighbor not in g_costs or tentative_g_cost < g_costs[neighbor]:
                came_from[neighbor] = current_node
                g_costs[neighbor] = tentative_g_cost
                f_costs[neighbor] = tentative_g_cost + heuristics[neighbor]
                heapq.heappush(open_list, (f_costs[neighbor], neighbor))

    return None  # No path found

# Function to read graph from user input
def read_graph():
    graph = {}
    while True:
        edge = input("Enter an edge (node1 node2 weight) or 'done' to finish: ")
        if edge == 'done':
            break
        node1, node2, weight = edge.split()
        weight = float(weight)  # convert weight to float
        if node1 not in graph:
            graph[node1] = []
        if node2 not in graph:
            graph[node2] = []
        graph[node1].append((node2, weight))
        graph[node2].append((node1, weight))  # Because the graph is undirected
    return graph

# Function to read heuristic values from user input
def read_heuristics():
    heuristics = {}
    while True:
        node = input("Enter node for heuristic value or 'done' to finish: ")
        if node == 'done':
            break
        heuristic_value = float(input(f"Enter heuristic value for {node}: "))
        heuristics[node] = heuristic_value
    return heuristics

# Main Execution
if __name__ == "__main__":
    # Read graph and heuristics from user input
    graph = read_graph()
    heuristics = read_heuristics()

    print("Graph Representation:", graph)
    print("Heuristic Values:", heuristics)

    # Take the starting and goal nodes from the user
    start_node = input("Enter the starting node for A* Search: ")
    goal_node = input("Enter the goal node for A* Search: ")

    # Perform A* algorithm and display the path
    path = a_star_algorithm(graph, heuristics, start_node, goal_node)
    if path:
        print("Path found:", path)
    else:
        print("No path found from", start_node, "to", goal_node)


Enter an edge (node1 node2 weight) or 'done' to finish:  a b 1
Enter an edge (node1 node2 weight) or 'done' to finish:  a c 2
Enter an edge (node1 node2 weight) or 'done' to finish:  b d 3
Enter an edge (node1 node2 weight) or 'done' to finish:  c d 1
Enter an edge (node1 node2 weight) or 'done' to finish:  done
Enter node for heuristic value or 'done' to finish:  a
Enter heuristic value for a:  3
Enter node for heuristic value or 'done' to finish:  b
Enter heuristic value for b:  2
Enter node for heuristic value or 'done' to finish:  c
Enter heuristic value for c:  1
Enter node for heuristic value or 'done' to finish:  d
Enter heuristic value for d:  0
Enter node for heuristic value or 'done' to finish:  done


Graph Representation: {'a': [('b', 1.0), ('c', 2.0)], 'b': [('a', 1.0), ('d', 3.0)], 'c': [('a', 2.0), ('d', 1.0)], 'd': [('b', 3.0), ('c', 1.0)]}
Heuristic Values: {'a': 3.0, 'b': 2.0, 'c': 1.0, 'd': 0.0}


Enter the starting node for A* Search:  a
Enter the goal node for A* Search:  d


Path found: ['a', 'c', 'd']


In [17]:
#########################    EXP 12     #####################
#Fuzzy set – union, intersection and complement with 3 fuzzy sets
# Fuzzy Set Operations
def fuzzy_union(A, B):
    """Return the union of two fuzzy sets A and B."""
    return {x: max(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_intersection(A, B):
    """Return the intersection of two fuzzy sets A and B."""
    return {x: min(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_complement(A):
    """Return the complement of a fuzzy set A."""
    return {x: 1 - A.get(x, 0) for x in A}

# Example fuzzy sets
A = {'x1': 0.3, 'x2': 0.7, 'x3': 0.5}
B = {'x1': 0.6, 'x2': 0.2, 'x3': 0.8}
C = {'x1': 0.4, 'x2': 0.9, 'x3': 0.3}

print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)
print("Fuzzy Set C:", C)

# 1. Union of three fuzzy sets
union_AB = fuzzy_union(A, B)
union_ABC = fuzzy_union(union_AB, C)

# 2. Intersection of three fuzzy sets
intersection_AB = fuzzy_intersection(A, B)
intersection_ABC = fuzzy_intersection(intersection_AB, C)

# 3. Complements of each set
complement_A = fuzzy_complement(A)
complement_B = fuzzy_complement(B)
complement_C = fuzzy_complement(C)

print("\nUnion of A, B, and C:", union_ABC)
print("Intersection of A, B, and C:", intersection_ABC)
print("Complement of A:", complement_A)
print("Complement of B:", complement_B)
print("Complement of C:", complement_C)


Fuzzy Set A: {'x1': 0.3, 'x2': 0.7, 'x3': 0.5}
Fuzzy Set B: {'x1': 0.6, 'x2': 0.2, 'x3': 0.8}
Fuzzy Set C: {'x1': 0.4, 'x2': 0.9, 'x3': 0.3}

Union of A, B, and C: {'x2': 0.9, 'x1': 0.6, 'x3': 0.8}
Intersection of A, B, and C: {'x2': 0.2, 'x1': 0.3, 'x3': 0.3}
Complement of A: {'x1': 0.7, 'x2': 0.30000000000000004, 'x3': 0.5}
Complement of B: {'x1': 0.4, 'x2': 0.8, 'x3': 0.19999999999999996}
Complement of C: {'x1': 0.6, 'x2': 0.09999999999999998, 'x3': 0.7}


In [36]:
#########################    EXP 13     #####################
# Fuzzy set De Morgan’s Law with 2 fuzzy sets.

# Fuzzy Set Operations
class FuzzySet:
    def __init__(self, elements, memberships):
        self.elements = elements
        self.memberships = memberships

    # Union of two fuzzy sets
    def union(self, other):
        result_elements = list(set(self.elements) | set(other.elements))
        result_memberships = {}
        for element in result_elements:
            membership_self = self.memberships.get(element, 0)
            membership_other = other.memberships.get(element, 0)
            result_memberships[element] = max(membership_self, membership_other)
        return FuzzySet(result_elements, result_memberships)

    # Intersection of two fuzzy sets
    def intersection(self, other):
        result_elements = list(set(self.elements) & set(other.elements))
        result_memberships = {}
        for element in result_elements:
            membership_self = self.memberships.get(element, 0)
            membership_other = other.memberships.get(element, 0)
            result_memberships[element] = min(membership_self, membership_other)
        return FuzzySet(result_elements, result_memberships)

    # Complement of the fuzzy set
    def complement(self):
        result_memberships = {element: 1 - membership for element, membership in self.memberships.items()}
        return FuzzySet(self.elements, result_memberships)

    # Print the fuzzy set
    def print_fuzzy_set(self):
        print("Fuzzy Set:")
        for element in self.elements:
            print(f"Element: {element}, Membership: {self.memberships.get(element, 0)}")
        print()

    # Check for equality within a tolerance range (due to floating point precision)
    def is_equal(self, other):
        tolerance = 1e-6  # Increased tolerance for floating point comparisons
        if self.elements != other.elements:
            return False
        for element in self.elements:
            if abs(self.memberships.get(element, 0) - other.memberships.get(element, 0)) > tolerance:
                return False
        return True

# Main execution
if __name__ == "__main__":
    # Fuzzy Set 1
    fuzzy_set_1 = FuzzySet(["a", "b", "c", "d"], {"a": 0.8, "b": 0.6, "c": 0.9, "d": 0.4})

    # Fuzzy Set 2
    fuzzy_set_2 = FuzzySet(["b", "c", "d", "e"], {"b": 0.7, "c": 0.5, "d": 0.8, "e": 0.3})

    # Perform Union, Intersection, and Complement
    print("Fuzzy Set 1:")
    fuzzy_set_1.print_fuzzy_set()

    print("Fuzzy Set 2:")
    fuzzy_set_2.print_fuzzy_set()

    # Union of fuzzy_set_1 and fuzzy_set_2
    union_set = fuzzy_set_1.union(fuzzy_set_2)
    print("Union of Fuzzy Set 1 and Fuzzy Set 2:")
    union_set.print_fuzzy_set()

    # Intersection of fuzzy_set_1 and fuzzy_set_2
    intersection_set = fuzzy_set_1.intersection(fuzzy_set_2)
    print("Intersection of Fuzzy Set 1 and Fuzzy Set 2:")
    intersection_set.print_fuzzy_set()

    # Complement of fuzzy_set_1
    complement_set_1 = fuzzy_set_1.complement()
    print("Complement of Fuzzy Set 1:")
    complement_set_1.print_fuzzy_set()

    # Union of all three sets (fuzzy_set_1, fuzzy_set_2, fuzzy_set_3)
    complement_union = fuzzy_set_1.union(fuzzy_set_2).complement()
    complement_fuzzy_set_1 = fuzzy_set_1.complement()
    complement_fuzzy_set_2 = fuzzy_set_2.complement()
    intersection_complement = complement_fuzzy_set_1.intersection(complement_fuzzy_set_2)

    # Demonstrating De Morgan's Law
    print("Demonstrating De Morgan's Law:")
    print("Complement of Union of Fuzzy Set 1 and Fuzzy Set 2:")
    complement_union.print_fuzzy_set()

    print("Intersection of Complements of Fuzzy Set 1 and Fuzzy Set 2:")
    intersection_complement.print_fuzzy_set()

    # Verify if they are the same
    if complement_union.is_equal(intersection_complement):
        print("De Morgan's Law holds: (A ∪ B)^C = A^C ∩ B^C")
    else:
        print("De Morgan's Law does not hold.")


Fuzzy Set 1:
Fuzzy Set:
Element: a, Membership: 0.8
Element: b, Membership: 0.6
Element: c, Membership: 0.9
Element: d, Membership: 0.4

Fuzzy Set 2:
Fuzzy Set:
Element: b, Membership: 0.7
Element: c, Membership: 0.5
Element: d, Membership: 0.8
Element: e, Membership: 0.3

Union of Fuzzy Set 1 and Fuzzy Set 2:
Fuzzy Set:
Element: d, Membership: 0.8
Element: c, Membership: 0.9
Element: e, Membership: 0.3
Element: b, Membership: 0.7
Element: a, Membership: 0.8

Intersection of Fuzzy Set 1 and Fuzzy Set 2:
Fuzzy Set:
Element: d, Membership: 0.4
Element: b, Membership: 0.6
Element: c, Membership: 0.5

Complement of Fuzzy Set 1:
Fuzzy Set:
Element: a, Membership: 0.19999999999999996
Element: b, Membership: 0.4
Element: c, Membership: 0.09999999999999998
Element: d, Membership: 0.6

Demonstrating De Morgan's Law:
Complement of Union of Fuzzy Set 1 and Fuzzy Set 2:
Fuzzy Set:
Element: d, Membership: 0.19999999999999996
Element: c, Membership: 0.09999999999999998
Element: e, Membership: 0.7
El

In [18]:
#########################    EXP 13     #####################
# Fuzzy set – union, intersection and complement. #Demonstrate De Morgan’s Law ( Complement of Union)

# Define two fuzzy sets A and B
A = {'x1': 0.2, 'x2': 0.7, 'x3': 0.5}
B = {'x1': 0.6, 'x2': 0.4, 'x3': 0.8}

# Fuzzy Union
def fuzzy_union(A, B):
    return {x: max(A[x], B[x]) for x in A}

# Fuzzy Intersection
def fuzzy_intersection(A, B):
    return {x: min(A[x], B[x]) for x in A}

# Fuzzy Complement
def fuzzy_complement(A):
    return {x: 1 - A[x] for x in A}

# Perform operations
union_AB = fuzzy_union(A, B)
intersection_AB = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
complement_B = fuzzy_complement(B)

# Demonstrate De Morgan's Law
complement_union = fuzzy_complement(union_AB)
intersection_of_complements = fuzzy_intersection(complement_A, complement_B)

# Print Results
print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)
print("\nUnion (A ∪ B):", union_AB)
print("Intersection (A ∩ B):", intersection_AB)
print("\nComplement of A:", complement_A)
print("Complement of B:", complement_B)
print("\nComplement of Union (A ∪ B)':", complement_union)
print("Intersection of Complements (A' ∩ B'):", intersection_of_complements)

# Check if De Morgan's law holds
print("\nDe Morgan's Law Verified:", complement_union == intersection_of_complements)


Fuzzy Set A: {'x1': 0.2, 'x2': 0.7, 'x3': 0.5}
Fuzzy Set B: {'x1': 0.6, 'x2': 0.4, 'x3': 0.8}

Union (A ∪ B): {'x1': 0.6, 'x2': 0.7, 'x3': 0.8}
Intersection (A ∩ B): {'x1': 0.2, 'x2': 0.4, 'x3': 0.5}

Complement of A: {'x1': 0.8, 'x2': 0.30000000000000004, 'x3': 0.5}
Complement of B: {'x1': 0.4, 'x2': 0.6, 'x3': 0.19999999999999996}

Complement of Union (A ∪ B)': {'x1': 0.4, 'x2': 0.30000000000000004, 'x3': 0.19999999999999996}
Intersection of Complements (A' ∩ B'): {'x1': 0.4, 'x2': 0.30000000000000004, 'x3': 0.19999999999999996}

De Morgan's Law Verified: True


In [21]:
#########################    EXP 14     #####################

# Fuzzy set  – union, intersection and complement #De Morgan’s Law ( Complement of Intersection)


# Fuzzy Set Operations: Union, Intersection, Complement
def fuzzy_union(A, B):
    """Return the union of two fuzzy sets A and B."""
    return {x: max(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_intersection(A, B):
    """Return the intersection of two fuzzy sets A and B."""
    return {x: min(A.get(x, 0), B.get(x, 0)) for x in set(A) | set(B)}

def fuzzy_complement(A):
    """Return the complement of a fuzzy set A."""
    return {x: 1 - A.get(x, 0) for x in A}

# Example fuzzy sets
A = {'x1': 0.3, 'x2': 0.8, 'x3': 0.5}
B = {'x1': 0.7, 'x2': 0.6, 'x3': 0.4}

print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)

# Operations
intersection_AB = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
complement_B = fuzzy_complement(B)

print("\nIntersection of A and B:", intersection_AB)
print("Complement of A:", complement_A)
print("Complement of B:", complement_B)

# Demonstrate De Morgan's Law (Complement of Intersection)
complement_intersection = fuzzy_complement(intersection_AB)
union_complements = fuzzy_union(complement_A, complement_B)

print("\nComplement of (A intersection B):", complement_intersection)
print("Union of (complement A and complement B):", union_complements)

# Check if De Morgan's Law holds
print("\nDe Morgan's Law Verified:", complement_intersection == union_complements)


Fuzzy Set A: {'x1': 0.3, 'x2': 0.8, 'x3': 0.5}
Fuzzy Set B: {'x1': 0.7, 'x2': 0.6, 'x3': 0.4}

Intersection of A and B: {'x2': 0.6, 'x1': 0.3, 'x3': 0.4}
Complement of A: {'x1': 0.7, 'x2': 0.19999999999999996, 'x3': 0.5}
Complement of B: {'x1': 0.30000000000000004, 'x2': 0.4, 'x3': 0.6}

Complement of (A intersection B): {'x2': 0.4, 'x1': 0.7, 'x3': 0.6}
Union of (complement A and complement B): {'x2': 0.4, 'x1': 0.7, 'x3': 0.6}

De Morgan's Law Verified: True


In [22]:
#########################    EXP 15     #####################

#Tic-Tac-Toe, computer wins or it is a draw.
import math

# Initialize empty board
def create_board():
    return [' ' for _ in range(9)]

# Display the board
def print_board(board):
    for row in [board[i*3:(i+1)*3] for i in range(3)]:
        print('| ' + ' | '.join(row) + ' |')

# Check if someone has won
def check_winner(board, player):
    win_conditions = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # Rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # Columns
        [0, 4, 8], [2, 4, 6]             # Diagonals
    ]
    for condition in win_conditions:
        if all(board[i] == player for i in condition):
            return True
    return False

# Check if the board is full (draw)
def is_full(board):
    return ' ' not in board

# Minimax Algorithm
def minimax(board, is_maximizing):
    if check_winner(board, 'X'):
        return 1
    if check_winner(board, 'O'):
        return -1
    if is_full(board):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'
                score = minimax(board, False)
                board[i] = ' '
                best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'
                score = minimax(board, True)
                board[i] = ' '
                best_score = min(score, best_score)
        return best_score

# Computer move using minimax
def computer_move(board):
    best_score = -math.inf
    move = None
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'X'
            score = minimax(board, False)
            board[i] = ' '
            if score > best_score:
                best_score = score
                move = i
    board[move] = 'X'

# Main game loop
def play_game():
    board = create_board()
    print("You are 'O'. Computer is 'X'.")
    print("Positions are numbered as:")
    print_board([str(i) for i in range(9)])

    while True:
        # Player move
        try:
            player_move = int(input("\nEnter your move (0-8): "))
            if board[player_move] != ' ':
                print("Position already taken! Try again.")
                continue
            board[player_move] = 'O'
        except (ValueError, IndexError):
            print("Invalid input. Enter a number between 0 and 8.")
            continue

        print("\nBoard after your move:")
        print_board(board)

        if check_winner(board, 'O'):
            print("\nYou win! (This should not happen 😅)")
            break
        if is_full(board):
            print("\nIt's a draw!")
            break

        # Computer move
        computer_move(board)
        print("\nBoard after computer's move:")
        print_board(board)

        if check_winner(board, 'X'):
            print("\nComputer wins!")
            break
        if is_full(board):
            print("\nIt's a draw!")
            break

# Start the game
if __name__ == "__main__":
    play_game()


You are 'O'. Computer is 'X'.
Positions are numbered as:
| 0 | 1 | 2 |
| 3 | 4 | 5 |
| 6 | 7 | 8 |



Enter your move (0-8):  0



Board after your move:
| O |   |   |
|   |   |   |
|   |   |   |

Board after computer's move:
| O |   |   |
|   | X |   |
|   |   |   |



Enter your move (0-8):  1



Board after your move:
| O | O |   |
|   | X |   |
|   |   |   |

Board after computer's move:
| O | O | X |
|   | X |   |
|   |   |   |



Enter your move (0-8):  6



Board after your move:
| O | O | X |
|   | X |   |
| O |   |   |

Board after computer's move:
| O | O | X |
| X | X |   |
| O |   |   |



Enter your move (0-8):  7



Board after your move:
| O | O | X |
| X | X |   |
| O | O |   |

Board after computer's move:
| O | O | X |
| X | X | X |
| O | O |   |

Computer wins!


In [23]:
#########################    EXP 16    #####################

#Tic-Tac-Toe computer loses or it is a draw.

import math

# Print the board
def print_board(board):
    print("\n")
    for i in range(0, 9, 3):
        print(" | ".join(board[i:i+3]))
        if i < 6:
            print("---------")

# Check for a winner
def check_winner(board, player):
    win_conditions = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # Rows
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # Columns
        [0, 4, 8], [2, 4, 6]              # Diagonals
    ]
    for condition in win_conditions:
        if all(board[i] == player for i in condition):
            return True
    return False

# Check if the board is full
def is_full(board):
    return ' ' not in board

# Minimax function
def minimax(board, is_maximizing, depth=0):
    if check_winner(board, 'X'):  # Computer wins
        return 1  # Return 1 to represent a loss for the computer
    if check_winner(board, 'O'):  # Player wins
        return -1  # Return -1 to represent a win for the player
    if is_full(board):            # Draw
        return 0

    if is_maximizing:  # Computer's turn (maximizing)
        best_score = math.inf  # Minimize score (computer prefers losing)
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'  # Make move
                score = minimax(board, False, depth + 1)  # Minimize player’s best move
                board[i] = ' '  # Undo move
                best_score = min(score, best_score)  # Minimize computer's score
        return best_score
    else:  # Player's turn (minimizing)
        best_score = -math.inf  # Maximize score (player wants to win)
        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'  # Make move
                score = minimax(board, True, depth + 1)  # Maximize computer’s worst move
                board[i] = ' '  # Undo move
                best_score = max(score, best_score)  # Maximize player’s score
        return best_score

# Computer makes a move using minimax
def computer_move(board):
    best_score = math.inf
    move = None
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'X'
            score = minimax(board, False)  # Minimize player's score
            board[i] = ' '  # Undo move
            if score < best_score:
                best_score = score
                move = i
    board[move] = 'X'
    return move

# Main game function
def play_game():
    board = [' ' for _ in range(9)]  # Initial empty board
    print("Welcome to Modified Tic-Tac-Toe!")

    while True:
        print_board(board)

        # Player's turn
        while True:
            try:
                move = int(input("Enter your move (0-8): "))
                if move < 0 or move > 8 or board[move] != ' ':
                    print("Invalid move, try again.")
                    continue
                break
            except ValueError:
                print("Invalid input, please enter a number between 0 and 8.")

        board[move] = 'O'

        if check_winner(board, 'O'):
            print_board(board)
            print("You win!")
            break
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

        # Computer's turn
        print("Computer's turn...")
        computer_move(board)

        if check_winner(board, 'X'):
            print_board(board)
            print("Computer wins! (Shouldn't happen in this version!)")
            break
        if is_full(board):
            print_board(board)
            print("It's a draw!")
            break

# Start the game
if __name__ == "__main__":
    play_game()



Welcome to Modified Tic-Tac-Toe!


  |   |  
---------
  |   |  
---------
  |   |  


Enter your move (0-8):  0


Computer's turn...


O | X |  
---------
  |   |  
---------
  |   |  


Enter your move (0-8):  4


Computer's turn...


O | X | X
---------
  | O |  
---------
  |   |  


Enter your move (0-8):  7


Computer's turn...


O | X | X
---------
X | O |  
---------
  | O |  


Enter your move (0-8):  8




O | X | X
---------
X | O |  
---------
  | O | O
You win!


In [24]:
#########################    EXP 17    #####################

# MLP with N binary inputs, two hidden layers and one binary output

import numpy as np

# Activation function (binary step function)
def binary_step(x):
    return np.where(x >= 0, 1, 0)

# Forward pass through the network
def forward_pass(x, weights1, bias1, weights2, bias2, weights3, bias3):
    hidden1 = binary_step(np.dot(x, weights1) + bias1)
    hidden2 = binary_step(np.dot(hidden1, weights2) + bias2)
    output = binary_step(np.dot(hidden2, weights3) + bias3)
    return output, hidden1, hidden2

# Input vector (example)
x = np.array([1, 0])  # you can make it general for N inputs

# Number of steps you want to perform
steps = 3  # you can change this as needed

for step in range(1, steps + 1):
    # Randomly initialize weights and biases in every iteration
    weights1 = np.random.randn(2, 4)   # input layer -> first hidden layer
    bias1 = np.random.randn(4)

    weights2 = np.random.randn(4, 3)   # first hidden layer -> second hidden layer
    bias2 = np.random.randn(3)

    weights3 = np.random.randn(3, 1)   # second hidden layer -> output layer
    bias3 = np.random.randn(1)

    # Perform forward pass
    output, hidden1, hidden2 = forward_pass(x, weights1, bias1, weights2, bias2, weights3, bias3)

    # Display output at each step
    print(f"\nStep {step}:")
    print("Input:", x)
    print("Hidden Layer 1 Output:", hidden1)
    print("Hidden Layer 2 Output:", hidden2)
    print("Final Output:", output)
    print("Weights1:\n", weights1)
    print("Bias1:\n", bias1)
    print("Weights2:\n", weights2)
    print("Bias2:\n", bias2)
    print("Weights3:\n", weights3)
    print("Bias3:\n", bias3)

print(f"\nTotal Steps Performed: {steps}")



Step 1:
Input: [1 0]
Hidden Layer 1 Output: [1 1 0 0]
Hidden Layer 2 Output: [1 1 0]
Final Output: [1]
Weights1:
 [[ 0.12517568  0.93299722 -0.0090305  -0.29298171]
 [ 1.21664946 -1.63212866  0.19919425 -0.20909216]]
Bias1:
 [-0.03889825  0.17850166 -0.61905156 -1.13167942]
Weights2:
 [[ 0.91838908 -0.57363036  0.21036175]
 [ 2.91563655  1.23320344 -0.58376811]
 [ 0.32719081 -0.75025462 -0.98871684]
 [ 0.82079487 -0.16543652  0.48499669]]
Bias2:
 [ 0.21120545 -0.30173658 -1.85431477]
Weights3:
 [[0.60072783]
 [0.49591716]
 [0.22936769]]
Bias3:
 [-0.47288837]

Step 2:
Input: [1 0]
Hidden Layer 1 Output: [0 1 1 1]
Hidden Layer 2 Output: [1 1 1]
Final Output: [1]
Weights1:
 [[-1.3714115  -0.10692896  0.77423555  0.57810111]
 [ 0.05381681  0.15200436 -0.57373752 -0.52182959]]
Bias1:
 [0.57586629 0.58758681 0.60879798 0.10620693]
Weights2:
 [[-1.14330598  1.28628398 -0.74511521]
 [ 0.37573271  0.3586884   1.62169834]
 [-0.00335369 -1.01252171  1.09317826]
 [ 1.16592447 -0.21741154  0.67222

In [25]:
#########################    EXP 18    #####################

# MLP with 4 binary inputs, one hidden layer and two binary outputs

import numpy as np

# Activation function (binary step function)
def binary_step(x):
    return np.where(x >= 0, 1, 0)

# Forward pass through the network
def forward_pass(x, weights1, bias1, weights2, bias2):
    hidden = binary_step(np.dot(x, weights1) + bias1)
    output = binary_step(np.dot(hidden, weights2) + bias2)
    return output, hidden

# Number of inputs
input_size = 4

# Number of neurons
hidden_layer_size = 3  # You can change if needed
output_size = 2

# Example input vector (4 binary inputs)
x = np.random.randint(0, 2, size=(input_size,))

# Number of steps you want to perform
steps = 3

for step in range(1, steps + 1):
    # Randomly initialize weights and biases
    weights1 = np.random.randn(input_size, hidden_layer_size)   # input -> hidden layer
    bias1 = np.random.randn(hidden_layer_size)

    weights2 = np.random.randn(hidden_layer_size, output_size)  # hidden layer -> output layer
    bias2 = np.random.randn(output_size)

    # Perform forward pass
    output, hidden = forward_pass(x, weights1, bias1, weights2, bias2)

    # Display outputs at each step
    print(f"\nStep {step}:")
    print("Input:", x)
    print("Hidden Layer Output:", hidden)
    print("Final Output (2 values):", output)
    print("Weights1 (Input to Hidden):\n", weights1)
    print("Bias1:\n", bias1)
    print("Weights2 (Hidden to Output):\n", weights2)
    print("Bias2:\n", bias2)

print(f"\nTotal Steps Performed: {steps}")



Step 1:
Input: [0 0 0 0]
Hidden Layer Output: [1 0 0]
Final Output (2 values): [0 0]
Weights1 (Input to Hidden):
 [[ 0.37028709 -0.46109229  2.03682964]
 [ 1.26595692 -0.41284316  0.96465981]
 [-0.1387365  -0.81163815 -0.57758503]
 [ 0.98070557  0.70074684  1.75853437]]
Bias1:
 [ 1.69779598 -0.9561313  -0.5550677 ]
Weights2 (Hidden to Output):
 [[-0.54197438  0.2569238 ]
 [-1.79415706 -1.5614437 ]
 [ 2.73965304 -0.95990004]]
Bias2:
 [-0.08678637 -0.56042629]

Step 2:
Input: [0 0 0 0]
Hidden Layer Output: [0 0 1]
Final Output (2 values): [0 1]
Weights1 (Input to Hidden):
 [[-0.42006199  0.23755611 -0.54630597]
 [-0.79632746  0.92377317  0.20535063]
 [-0.48093404  0.81326676  0.05160565]
 [ 0.43752385 -0.87578839  1.70881754]]
Bias1:
 [-1.46061616 -1.74331418  0.28048463]
Weights2 (Hidden to Output):
 [[-1.75081729 -0.00855364]
 [-1.4079037   0.06143026]
 [-0.63449128  1.54064779]]
Bias2:
 [0.3520812  1.34844653]

Step 3:
Input: [0 0 0 0]
Hidden Layer Output: [1 1 1]
Final Output (2 val

In [26]:
#########################    EXP 19    #####################

# MLP with N binary inputs, two hidden layers and one output. Use backpropagation and Sigmoid function



"""Implement a simple Multi-Layer Perceptron with N binary inputs, two
hidden layers and one output. Use backpropagation and Sigmoid function
as activation function. """

import numpy as np

# Sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

# Binary Cross-Entropy Loss
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true*np.log(y_pred+1e-8) + (1 - y_true)*np.log(1 - y_pred + 1e-8))

# MLP class
class MLP:
    def __init__(self, input_size, hidden1_size, hidden2_size, learning_rate=0.1):
        self.lr = learning_rate

        self.w1 = np.random.randn(input_size, hidden1_size)
        self.b1 = np.zeros((1, hidden1_size))

        self.w2 = np.random.randn(hidden1_size, hidden2_size)
        self.b2 = np.zeros((1, hidden2_size))

        self.w3 = np.random.randn(hidden2_size, 1)
        self.b3 = np.zeros((1, 1))

    def forward(self, X):
        self.z1 = np.dot(X, self.w1) + self.b1
        self.a1 = sigmoid(self.z1)

        self.z2 = np.dot(self.a1, self.w2) + self.b2
        self.a2 = sigmoid(self.z2)

        self.z3 = np.dot(self.a2, self.w3) + self.b3
        self.a3 = sigmoid(self.z3)

        return self.a3

    def backward(self, X, y, output):
        m = X.shape[0]
        error = output - y

        dz3 = error * sigmoid_derivative(self.z3)
        dw3 = np.dot(self.a2.T, dz3) / m
        db3 = np.sum(dz3, axis=0, keepdims=True) / m

        dz2 = np.dot(dz3, self.w3.T) * sigmoid_derivative(self.z2)
        dw2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0, keepdims=True) / m

        dz1 = np.dot(dz2, self.w2.T) * sigmoid_derivative(self.z1)
        dw1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0, keepdims=True) / m

        # Update weights
        self.w3 -= self.lr * dw3
        self.b3 -= self.lr * db3

        self.w2 -= self.lr * dw2
        self.b2 -= self.lr * db2

        self.w1 -= self.lr * dw1
        self.b1 -= self.lr * db1

    def train(self, X, y, epochs=10000, verbose=False):
        for epoch in range(epochs):
            output = self.forward(X)
            loss = binary_cross_entropy(y, output)
            self.backward(X, y, output)
            if verbose and epoch % 1000 == 0:
                print(f"Epoch {epoch}, Loss: {loss:.4f}")
        print("Training complete.")

# Sample binary input data (N = 3)
X = np.array([
    [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

y = np.array([[0], [1], [1], [0]])  # XOR-like output

# Create and train model
mlp = MLP(input_size=3, hidden1_size=4, hidden2_size=3, learning_rate=0.5)
mlp.train(X, y, epochs=10000, verbose=True)

# Final outputs
print("\nPredictions:")
print(mlp.forward(X))

print("\nFinal weights and biases:")
print("w1:\n", mlp.w1)
print("b1:\n", mlp.b1)
print("w2:\n", mlp.w2)
print("b2:\n", mlp.b2)
print("w3:\n", mlp.w3)
print("b3:\n", mlp.b3)

Epoch 0, Loss: 0.6628
Epoch 1000, Loss: 0.1945
Epoch 2000, Loss: 0.0625
Epoch 3000, Loss: 0.0416
Epoch 4000, Loss: 0.0327
Epoch 5000, Loss: 0.0276
Epoch 6000, Loss: 0.0242
Epoch 7000, Loss: 0.0218
Epoch 8000, Loss: 0.0200
Epoch 9000, Loss: 0.0185
Training complete.

Predictions:
[[0.0137044 ]
 [0.98262792]
 [0.98218135]
 [0.01964019]]

Final weights and biases:
w1:
 [[ 1.70512818 -0.83143756 -1.46424312 -2.4632222 ]
 [ 1.75696713 -0.06068882 -2.29376658 -2.65313089]
 [-2.60535968  1.2284938  -2.69553471  3.81409117]]
b1:
 [[ 0.16845649 -0.32851521  0.97433812 -0.11202258]]
w2:
 [[-2.2558105  -0.38252041  3.13431951]
 [ 0.55220984 -0.68347492 -0.84906996]
 [-1.72233968 -0.31065308  3.24172348]
 [ 3.35621061 -0.68747181 -4.32781832]]
b2:
 [[-0.55932586  0.00118328  0.61894721]]
w3:
 [[ 4.99666441]
 [-0.16101538]
 [-6.73382359]]
b3:
 [[0.72918497]]


In [27]:
#########################    EXP 20    #####################

# MLP with N binary inputs, two hidden layers and one output. Use backpropagation and ReLU function as activation function.

import numpy as np

# ReLU activation function and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

# Sigmoid activation function and its derivative (used in the output layer)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

# Binary Cross-Entropy Loss function
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-8) + (1 - y_true) * np.log(1 - y_pred + 1e-8))

# MLP class with forward and backward propagation
class MLP:
    def __init__(self, input_size, hidden1_size, hidden2_size, learning_rate=0.1):
        self.lr = learning_rate
        self.w1 = np.random.randn(input_size, hidden1_size)
        self.b1 = np.zeros((1, hidden1_size))

        self.w2 = np.random.randn(hidden1_size, hidden2_size)
        self.b2 = np.zeros((1, hidden2_size))

        self.w3 = np.random.randn(hidden2_size, 1)
        self.b3 = np.zeros((1, 1))

    def forward(self, X):
        # Forward pass: input -> hidden1 -> hidden2 -> output
        self.z1 = np.dot(X, self.w1) + self.b1
        self.a1 = relu(self.z1)

        self.z2 = np.dot(self.a1, self.w2) + self.b2
        self.a2 = relu(self.z2)

        self.z3 = np.dot(self.a2, self.w3) + self.b3
        self.a3 = sigmoid(self.z3)  # Output layer
        return self.a3

    def backward(self, X, y, output):
        m = X.shape[0]

        # Calculate the error
        error = output - y

        # Backpropagation step by step
        dz3 = error * sigmoid_derivative(self.z3)
        dw3 = np.dot(self.a2.T, dz3) / m
        db3 = np.sum(dz3, axis=0, keepdims=True) / m

        dz2 = np.dot(dz3, self.w3.T) * relu_derivative(self.z2)
        dw2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0, keepdims=True) / m

        dz1 = np.dot(dz2, self.w2.T) * relu_derivative(self.z1)
        dw1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0, keepdims=True) / m

        # Update the weights and biases using gradient descent
        self.w3 -= self.lr * dw3
        self.b3 -= self.lr * db3

        self.w2 -= self.lr * dw2
        self.b2 -= self.lr * db2

        self.w1 -= self.lr * dw1
        self.b1 -= self.lr * db1

    def train(self, X, y, epochs=10000, verbose=False):
        for epoch in range(epochs):
            output = self.forward(X)
            loss = binary_cross_entropy(y, output)
            self.backward(X, y, output)
            if verbose and epoch % 1000 == 0:
                print(f"Epoch {epoch}, Loss: {loss:.4f}")
        print("Training complete.")

if __name__ == "__main__":
    # Sample data: XOR-like problem with 3 binary inputs
    X = np.array([
        [0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1],
    ])

    # Target values for XOR problem
    y = np.array([[0], [1], [1], [0]])

    # Create and train the MLP model
    mlp = MLP(input_size=3, hidden1_size=5, hidden2_size=3, learning_rate=0.1)
    mlp.train(X, y, epochs=10000, verbose=True)

    # Show predictions after training
    print("\nPredictions after training:")
    predictions = np.round(mlp.forward(X), 3)
    print(predictions)

    # Display final weights and biases
    print("\nFinal weights and biases:")
    print("w1:\n", mlp.w1)
    print("b1:\n", mlp.b1)
    print("w2:\n", mlp.w2)
    print("b2:\n", mlp.b2)
    print("w3:\n", mlp.w3)
    print("b3:\n", mlp.b3)


Epoch 0, Loss: 0.7112
Epoch 1000, Loss: 0.0788
Epoch 2000, Loss: 0.0418
Epoch 3000, Loss: 0.0303
Epoch 4000, Loss: 0.0244
Epoch 5000, Loss: 0.0208
Epoch 6000, Loss: 0.0183
Epoch 7000, Loss: 0.0165
Epoch 8000, Loss: 0.0151
Epoch 9000, Loss: 0.0139
Training complete.

Predictions after training:
[[0.02 ]
 [0.991]
 [0.991]
 [0.014]]

Final weights and biases:
w1:
 [[-1.08967692e+00  4.30896771e-01  9.36378972e-01 -1.35744819e+00
  -1.55013344e+00]
 [-5.97390517e-04 -5.03919126e-01  4.87130106e-01 -1.25751813e+00
  -7.32003032e-02]
 [-1.22386323e+00  9.95202770e-01 -1.51825211e+00  2.50296632e+00
  -4.76409576e-01]]
b1:
 [[ 0.         -0.10572034  0.          0.1119991   0.        ]]
w2:
 [[-0.35771118  0.03676079  1.47527073]
 [ 0.63369116  1.30126904  0.33158004]
 [ 0.01857126  0.65931953  1.63549501]
 [-0.53626304  1.36642625  2.41686556]
 [-0.74910746 -1.26853296  0.69701592]]
b2:
 [[ 1.39996748 -0.26982119 -0.27072922]]
w3:
 [[-1.65931089]
 [ 0.81789325]
 [ 1.99259392]]
b3:
 [[-1.6933

In [28]:
#########################    EXP 21    #####################

# MLP with with N binary inputs, two hidden layers and one output. Use backpropagation and Tanh function as activation function.


import numpy as np

# Tanh and its derivative
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1.0 - np.tanh(x)**2

# MLP class with backpropagation and Tanh activation
class MLP:
    def __init__(self, input_size, hidden1_size, hidden2_size):
        # Randomly initialize weights and biases
        self.w1 = np.random.randn(input_size, hidden1_size)  # Weights for first layer
        self.b1 = np.zeros((1, hidden1_size))  # Bias for first layer

        self.w2 = np.random.randn(hidden1_size, hidden2_size)  # Weights for second layer
        self.b2 = np.zeros((1, hidden2_size))  # Bias for second layer

        self.w3 = np.random.randn(hidden2_size, 1)  # Weights for output layer
        self.b3 = np.zeros((1, 1))  # Bias for output layer

    def forward(self, X):
        # Forward pass (compute activations for each layer)
        self.z1 = np.dot(X, self.w1) + self.b1
        self.a1 = tanh(self.z1)

        self.z2 = np.dot(self.a1, self.w2) + self.b2
        self.a2 = tanh(self.z2)

        self.z3 = np.dot(self.a2, self.w3) + self.b3
        self.a3 = self.z3  # No activation on the output layer for binary classification (regression output)
        return self.a3

    def backprop(self, X, y, learning_rate):
        # Backpropagation (gradient descent)
        m = X.shape[0]  # Number of examples

        # Output layer error
        error_output = self.a3 - y
        d_w3 = np.dot(self.a2.T, error_output) / m
        d_b3 = np.sum(error_output) / m

        # Second hidden layer error
        error_hidden2 = np.dot(error_output, self.w3.T) * tanh_derivative(self.z2)
        d_w2 = np.dot(self.a1.T, error_hidden2) / m
        d_b2 = np.sum(error_hidden2) / m

        # First hidden layer error
        error_hidden1 = np.dot(error_hidden2, self.w2.T) * tanh_derivative(self.z1)
        d_w1 = np.dot(X.T, error_hidden1) / m
        d_b1 = np.sum(error_hidden1) / m

        # Update weights and biases
        self.w1 -= learning_rate * d_w1
        self.b1 -= learning_rate * d_b1
        self.w2 -= learning_rate * d_w2
        self.b2 -= learning_rate * d_b2
        self.w3 -= learning_rate * d_w3
        self.b3 -= learning_rate * d_b3

    def train(self, X, y, epochs, learning_rate):
        # Training loop with backpropagation
        for epoch in range(epochs):
            self.forward(X)
            self.backprop(X, y, learning_rate)

            if epoch % 1000 == 0:
                loss = np.mean((self.a3 - y)**2)
                print(f"Epoch {epoch}, Loss: {loss:.4f}")
        print("Training complete.")

if __name__ == "__main__":
    # Sample XOR-like input (with binary inputs)
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1],
    ])

    # Expected output (binary classification for XOR)
    y = np.array([
        [0],
        [1],
        [1],
        [0],
    ])

    # Create the model
    input_size = X.shape[1]  # Number of input features (N binary inputs)
    hidden1_size = 4         # Number of neurons in the first hidden layer
    hidden2_size = 3         # Number of neurons in the second hidden layer

    mlp = MLP(input_size, hidden1_size, hidden2_size)

    # Train the model
    epochs = 10000
    learning_rate = 0.1
    mlp.train(X, y, epochs, learning_rate)

    # Predictions after training
    predictions = mlp.forward(X)
    print("\nPredictions after training:")
    print(np.round(predictions, 3))

    # Final weights and biases
    print("\nFinal weights and biases:")
    print("w1:\n", mlp.w1)
    print("b1:\n", mlp.b1)
    print("w2:\n", mlp.w2)
    print("b2:\n", mlp.b2)
    print("w3:\n", mlp.w3)
    print("b3:\n", mlp.b3)


Epoch 0, Loss: 2.2426
Epoch 1000, Loss: 0.0000
Epoch 2000, Loss: 0.0000
Epoch 3000, Loss: 0.0000
Epoch 4000, Loss: 0.0000
Epoch 5000, Loss: 0.0000
Epoch 6000, Loss: 0.0000
Epoch 7000, Loss: 0.0000
Epoch 8000, Loss: 0.0000
Epoch 9000, Loss: 0.0000
Training complete.

Predictions after training:
[[0.]
 [1.]
 [1.]
 [0.]]

Final weights and biases:
w1:
 [[ 0.67214665  2.34042569 -0.26611944  1.28505524]
 [ 0.7430681  -0.21131517 -0.71262621  1.16174958]]
b1:
 [[0.24503122 0.24503122 0.24503122 0.24503122]]
w2:
 [[-0.4868978  -0.7448623  -0.59238286]
 [ 0.68077265  0.57208819 -0.59604135]
 [-1.44370287 -1.45054295  0.34627394]
 [-1.04290617  1.47424445 -1.49939806]]
b2:
 [[0.41939155 0.41939155 0.41939155]]
w3:
 [[-1.58743962]
 [-0.14606547]
 [-1.23304703]]
b3:
 [[-0.329308]]


In [33]:
#########################    EXP 22    #####################

'''Write a program to read a text file with at least 30 sentences and 200 words
and perform the following tasks in the given sequence.
a. Text cleaning by removing punctuation/special characters, numbers
and extra white spaces. Use regular expression for the same.
b. Convert text to lowercase
c. Tokenization
d. Remove stop words
e. Correct misspelled words'''

# import re
# import nltk
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from spellchecker import SpellChecker

# # Download required NLTK data
# nltk.download('punkt')
# nltk.download('stopwords')

# def clean_text(text):
#     """Remove punctuation, special characters, numbers, and extra whitespaces."""
#     text = re.sub(r'[^a-zA-Z\s]', '', text)  # keep only letters and spaces
#     text = re.sub(r'\s+', ' ', text)  # replace multiple spaces with single space
#     return text.strip()

# def main():
#     # Step 1: Get file path input from user
#     file_path = input("Enter the path of the text file you want to process: ").strip()

#     try:
#         # Step 2: Read the text file
#         with open(file_path, 'r', encoding='utf-8') as file:
#             text = file.read()

#         # Step 3: Clean the text
#         cleaned_text = clean_text(text)

#         # Step 4: Convert text to lowercase
#         cleaned_text = cleaned_text.lower()

#         # Step 5: Tokenization
#         tokens = word_tokenize(cleaned_text)

#         # Step 6: Remove stopwords
#         stop_words = set(stopwords.words('english'))
#         tokens_without_stopwords = [word for word in tokens if word not in stop_words]

#         # Step 7: Correct misspelled words
#         spell = SpellChecker()
#         corrected_tokens = [spell.correction(word) if spell.correction(word) else word for word in tokens_without_stopwords]

#         # Final Output
#         print("\nCleaned and Processed Tokens:\n")
#         print(corrected_tokens)

#     except FileNotFoundError:
#         print(f"Error: File not found at path '{file_path}'. Please check and try again.")

# if __name__ == "__main__":
#     main()


!pip install pyspellchecker
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from spellchecker import SpellChecker
import os

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# Path to file inside "CSV Files" folder
file_path = os.path.join("CSV Files", r"C:\Users\shank\Downloads\nlpTextFile.txt")

# Step a: Read and clean the text
with open(file_path, 'r', encoding='utf-8') as file:
    text = file.read()

# Remove punctuation, numbers, and special characters
text = re.sub(r'[^A-Za-z\s]', '', text)
text = re.sub(r'\s+', ' ', text)  # Remove extra spaces
# print("Cleaned Text:\n", text[:500])  # Print first 500 characters of cleaned text
# Step b: Convert to lowercase
text = text.lower()

# Step c: Tokenization (no sentence split to avoid punkt_tab error)
tokens = word_tokenize(text)

# Step d: Remove stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]

# Step e: Correct spelling
spell = SpellChecker()
corrected_tokens = [spell.correction(word) for word in filtered_tokens]

# Final Output
print("Original Tokens:\n", tokens[:50])
print("\nFiltered Tokens (no stopwords):\n", filtered_tokens[:50])
print("\nCorrected Tokens:\n", corrected_tokens[:50])


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Original Tokens:
 ['artificial', 'intelligence', 'is', 'rapidly', 'changing', 'the', 'world', 'every', 'day', 'new', 'advancements', 'are', 'made', 'in', 'machine', 'learning', 'and', 'deep', 'learning', 'these', 'technologies', 'are', 'helping', 'businesses', 'make', 'smarter', 'decisions', 'they', 'are', 'also', 'improving', 'healthcare', 'education', 'and', 'entertainment', 'industries', 'however', 'with', 'great', 'power', 'comes', 'great', 'responsibility', 'ethical', 'concerns', 'around', 'ai', 'are', 'growing', 'among']

Filtered Tokens (no stopwords):
 ['artificial', 'intelligence', 'rapidly', 'changing', 'world', 'every', 'day', 'new', 'advancements', 'made', 'machine', 'learning', 'deep', 'learning', 'technologies', 'helping', 'businesses', 'make', 'smarter', 'decisions', 'also', 'improving', 'healthcare', 'education', 'entertainment', 'industries', 'however', 'great', 'power', 'comes', 'great', 'responsibility', 'ethical', 'concerns', 'around', 'ai', 'growing', 'among', 'exp

In [35]:
#########################    EXP 23    #####################

'''Write a program to read a text file with at least 30 sentences and 200 words
and perform the following tasks in the given sequence.
a. Text cleaning by removing punctuation/special characters, numbers
and extra white spaces. Use regular expression for the same.
b. Convert text to lowercase
c. Stemming and Lemmatization
d. Create a list of 3 consecutive words after lemmatization'''

import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.util import ngrams
from nltk.corpus import stopwords

# Download required NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def clean_text(text):
    """Remove punctuation, special characters, numbers, and extra whitespaces."""
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Keep only letters and spaces
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text.strip()

def main():
    # Step 1: Get file path input from user
    file_path = input("Enter the path of the text file you want to process: ").strip()

    try:
        # Step 2: Read the text file
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()

        # Step 3: Clean the text
        cleaned_text = clean_text(text)

        # Step 4: Convert text to lowercase
        cleaned_text = cleaned_text.lower()

        # Step 5: Tokenization
        tokens = word_tokenize(cleaned_text)

        # Step 6: Remove stopwords
        stop_words = set(stopwords.words('english'))
        tokens = [word for word in tokens if word not in stop_words]

        # Step 7: Stemming and Lemmatization
        # Using PorterStemmer for stemming
        stemmer = PorterStemmer()
        stemmed_tokens = [stemmer.stem(word) for word in tokens]

        # Using WordNetLemmatizer for lemmatization
        lemmatizer = WordNetLemmatizer()
        lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]

        # Step 8: Create a list of 3 consecutive words (bigrams) after lemmatization
        trigrams = list(ngrams(lemmatized_tokens, 3))

        # Final Output
        print("\nCleaned and Processed Trigrams (3 Consecutive Words) After Lemmatization:\n")
        print(trigrams)

    except FileNotFoundError:
        print(f"Error: File not found at path '{file_path}'. Please check and try again.")

if __name__ == "__main__":
    main()


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\shank\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Enter the path of the text file you want to process:  C:\Users\shank\Downloads\nlpTextFile.txt



Cleaned and Processed Trigrams (3 Consecutive Words) After Lemmatization:

[('artificial', 'intelligence', 'rapidly'), ('intelligence', 'rapidly', 'changing'), ('rapidly', 'changing', 'world'), ('changing', 'world', 'every'), ('world', 'every', 'day'), ('every', 'day', 'new'), ('day', 'new', 'advancement'), ('new', 'advancement', 'made'), ('advancement', 'made', 'machine'), ('made', 'machine', 'learning'), ('machine', 'learning', 'deep'), ('learning', 'deep', 'learning'), ('deep', 'learning', 'technology'), ('learning', 'technology', 'helping'), ('technology', 'helping', 'business'), ('helping', 'business', 'make'), ('business', 'make', 'smarter'), ('make', 'smarter', 'decision'), ('smarter', 'decision', 'also'), ('decision', 'also', 'improving'), ('also', 'improving', 'healthcare'), ('improving', 'healthcare', 'education'), ('healthcare', 'education', 'entertainment'), ('education', 'entertainment', 'industry'), ('entertainment', 'industry', 'however'), ('industry', 'however', 'great

In [37]:
#########################    EXP 24    #####################

'''Write a program to read a 3 text files on any technical concept with at least
20 sentences and 150 words. Implement one-hot encoding.
'''


import os
import re
from sklearn.preprocessing import OneHotEncoder
import numpy as np

folder_path="CSV Files"

# Define file paths relative to the folder
file_paths = [
    os.path.join(folder_path, r"C:\Users\shank\Downloads\nlp3TextFilePart1.txt"),
    os.path.join(folder_path, r"C:\Users\shank\Downloads\nlp3TextFilePart2.txt"),
    os.path.join(folder_path, r"C:\Users\shank\Downloads\nlp3TextFilePart3.txt")
]

# Step 1: Read and clean text from files
texts = []
for file_path in file_paths:
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
        # Remove non-alphabetical characters and convert to lowercase
        text = re.sub(r'[^A-Za-z\s]', '', text).lower()
        texts.append(text)

# Combine all texts into a single list of words
words = []
for text in texts:
    words.extend(text.split())

# Step 2: Create a set of unique words
unique_words = sorted(set(words))

# Step 3: One-hot encoding using sklearn
encoder = OneHotEncoder(sparse_output=False)
word_matrix = encoder.fit_transform(np.array(unique_words).reshape(-1, 1))

# Display the one-hot encoded matrix (show first 10 rows for brevity)
print("One-Hot Encoding for the first 10 unique words:")
for i in range(min(10, len(unique_words))):
    print(f"Word: {unique_words[i]} -> One-Hot Encoding: {word_matrix[i]}")

# Optionally save the matrix to a CSV file for future reference
# np.savetxt("one_hot_encoded_words.csv", word_matrix, delimiter=",", fmt="%d")

One-Hot Encoding for the first 10 unique words:
Word: a -> One-Hot Encoding: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
Word: ability -> One-Hot Encoding: [0. 1. 

In [39]:
#########################    EXP 25    #####################

#3 text files on a movie review with at least 20 sentences and 150 words. Implement bag of words.
"""Write a program to read a 3 text files on a movie review with at least 20
sentences and 150 words. Implement bag of words. """

import os
import re
from sklearn.feature_extraction.text import CountVectorizer

# Folder where your 3 text files are stored
folder_path = os.path.join("CSV Files")

# List to store text from selected review files
documents = []

# Specify only the 3 review file names you want
review_files = [r"C:\Users\shank\Downloads\nlp3TextFilePart1.txt", r"C:\Users\shank\Downloads\nlp3TextFilePart2.txt", r"C:\Users\shank\Downloads\nlp3TextFilePart3.txt"]

# Read each review file
for filename in review_files:
    file_path = os.path.join(folder_path, filename)
    if os.path.exists(file_path):  # Check if file actually exists
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()
            # Clean text: remove special characters and extra spaces
            text = re.sub(r'[^A-Za-z\s]', '', text)
            text = re.sub(r'\s+', ' ', text)
            text = text.lower()
            documents.append(text)
    else:
        print(f"Warning: {filename} not found!")

# Step 2: Bag of Words using CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Step 3: Show Results
print("Feature Names (Vocabulary):")
print(vectorizer.get_feature_names_out())

print("\nBag of Words Matrix:")
print(X.toarray())


Feature Names (Vocabulary):
['ability' 'about' 'access' 'actions' 'advanced' 'advancements'
 'advantages' 'agent' 'ai' 'algorithms' 'all' 'allowing' 'allows' 'also'
 'amazon' 'amounts' 'an' 'analysis' 'analyzed' 'and' 'anomalies'
 'anywhere' 'applications' 'are' 'artificial' 'as' 'authentication'
 'automatically' 'autonomous' 'aws' 'azure' 'based' 'be' 'being'
 'benefits' 'best' 'bias' 'box' 'businesses' 'by' 'can' 'categorized'
 'challenges' 'characteristics' 'charts' 'classified' 'classify' 'cleaned'
 'cleaning' 'cloud' 'collaboration' 'common' 'communicate' 'complex'
 'computer' 'computers' 'computing' 'concern' 'constantly' 'correcting'
 'cost' 'costeffective' 'critical' 'customers' 'data' 'deals' 'decision'
 'decisions' 'deep' 'delivers' 'delivery' 'descriptive' 'despite'
 'developing' 'deviation' 'discover' 'down' 'driving' 'duplicates'
 'easily' 'eda' 'effective' 'effectively' 'efficiency' 'enables'
 'encryption' 'errors' 'essential' 'excel' 'explicitly' 'exploratory'
 'face' 'f

In [41]:
#########################    EXP 26    #####################

#Write a program to read a 3 text files a tourist place with at least 20 sentences and 150 words. Implement TF-IDF.

import os
import re
from sklearn.feature_extraction.text import TfidfVectorizer

# Folder where your 3 text files are stored
folder_path = os.path.join("CSV Files")

# List to store text from selected tourist place files
documents = []

# Specify only the 3 review file names you want
tourist_files = [r"C:\Users\shank\Downloads\nlp3TextFilePart1.txt", r"C:\Users\shank\Downloads\nlp3TextFilePart2.txt", r"C:\Users\shank\Downloads\nlp3TextFilePart3.txt"]

# Read each tourist file
for filename in tourist_files:
    file_path = os.path.join(folder_path, filename)
    if os.path.exists(file_path):  # Check if file actually exists
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()
            # Clean text: remove special characters and extra spaces
            text = re.sub(r'[^A-Za-z\s]', '', text)
            text = re.sub(r'\s+', ' ', text)
            text = text.lower()
            documents.append(text)
    else:
        print(f"Warning: {filename} not found!")

# Step 2: TF-IDF using TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Step 3: Show Results
print("Feature Names (Vocabulary):")
print(vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(X.toarray())


Feature Names (Vocabulary):
['ability' 'about' 'access' 'actions' 'advanced' 'advancements'
 'advantages' 'agent' 'ai' 'algorithms' 'all' 'allowing' 'allows' 'also'
 'amazon' 'amounts' 'an' 'analysis' 'analyzed' 'and' 'anomalies'
 'anywhere' 'applications' 'are' 'artificial' 'as' 'authentication'
 'automatically' 'autonomous' 'aws' 'azure' 'based' 'be' 'being'
 'benefits' 'best' 'bias' 'box' 'businesses' 'by' 'can' 'categorized'
 'challenges' 'characteristics' 'charts' 'classified' 'classify' 'cleaned'
 'cleaning' 'cloud' 'collaboration' 'common' 'communicate' 'complex'
 'computer' 'computers' 'computing' 'concern' 'constantly' 'correcting'
 'cost' 'costeffective' 'critical' 'customers' 'data' 'deals' 'decision'
 'decisions' 'deep' 'delivers' 'delivery' 'descriptive' 'despite'
 'developing' 'deviation' 'discover' 'down' 'driving' 'duplicates'
 'easily' 'eda' 'effective' 'effectively' 'efficiency' 'enables'
 'encryption' 'errors' 'essential' 'excel' 'explicitly' 'exploratory'
 'face' 'f